// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBiBMKjeV56Sg99CTN0FOjhpCa-8B7Cew',
    appId: '1:206844954617:web:f6a3321f6de313a12a1f28',
    messagingSenderId: '206844954617',
    projectId: 'fluttershare-c5956',
    authDomain: 'fluttershare-c5956.firebaseapp.com',
    storageBucket: 'fluttershare-c5956.appspot.com',
    measurementId: 'G-DXWBP4N4X0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAd7oddSeR08_JPUFc-HJW-I3S9h0hv31U',
    appId: '1:206844954617:android:ff2e154f3363b2fe2a1f28',
    messagingSenderId: '206844954617',
    projectId: 'fluttershare-c5956',
    storageBucket: 'fluttershare-c5956.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAfYbI4RDv700vpcFI-NaWI8Clm-Xkhjg4',
    appId: '1:206844954617:ios:123da48519f937892a1f28',
    messagingSenderId: '206844954617',
    projectId: 'fluttershare-c5956',
    storageBucket: 'fluttershare-c5956.appspot.com',
    iosClientId: '206844954617-2cj6r052808dedcn475dktcohgomdufk.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAfYbI4RDv700vpcFI-NaWI8Clm-Xkhjg4',
    appId: '1:206844954617:ios:123da48519f937892a1f28',
    messagingSenderId: '206844954617',
    projectId: 'fluttershare-c5956',
    storageBucket: 'fluttershare-c5956.appspot.com',
    iosClientId: '206844954617-2cj6r052808dedcn475dktcohgomdufk.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagram',
  );
}
